<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

SELECT
  s.orderdate,
  COUNT(DISTINCT s.customerkey) AS total_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Europe' THEN s.customerkey END) AS eu_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'North America' THEN s.customerkey END) AS na_customers,
  COUNT(DISTINCT CASE WHEN c.continent = 'Australia' THEN s.customerkey END) AS au_customers
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY s.orderdate
ORDER BY s.orderdate;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_customers  na_customers  au_customers
0    2023-01-01               12             6             5             1
1    2023-01-02               49            15            31             3
2    2023-01-03               64            17            44             3
3    2023-01-04               78            28            46             4
4    2023-01-05               87            22            57             8
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26            41             6
360  2023-12-28               75            24            44             7
361  2023-12-29               55            19            32             4
362  2023-12-30               91            25            50            16
363  2023-12-31                9             1             8             0

[364 rows x 5 columns]

In [8]:
%%sql

SELECT
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) AS net_revenue,
  SUM(CASE WHEN EXTRACT(YEAR FROM s.orderdate) = 2022 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS revenue_2022,
  SUM(CASE WHEN EXTRACT(YEAR FROM s.orderdate) = 2023 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS revenue_2023
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
GROUP BY p.categoryname
ORDER BY p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revenue  revenue_2022  revenue_2023
0                          Audio   5312898.10     766938.21     688690.18
1        Cameras and camcorders   18520360.66    2382532.56    1983546.29
2                    Cell phones  32624265.72    8119665.07    6002147.63
3                      Computers  90619022.05   17862213.49   11650867.21
4                 Games and Toys   1668574.13     316127.30     270374.96
5                Home Appliances  26607245.54    6612446.68    5919992.87
6  Music, Movies and Audio Books  10588311.00    2989297.28    2180768.13
7                   TV and Video  20466861.38    5815336.61    4412178.23

In [20]:
%%sql
/*
Calculate the total number of unique male and female customers who made purchases in each store in 2023.
This will help in understanding the gender distribution of customers across different stores.

Use COUNT with CASE WHEN to count male and female customers separately.
Group the results by storecode and order them by storecode.
*/

SELECT
  st.storecode,
  COUNT(DISTINCT CASE WHEN c.gender = 'male' THEN s.customerkey ELSE 0 END) AS total_male_customers,
  COUNT(DISTINCT CASE WHEN c.gender = 'female' THEN s.customerkey ELSE 0 END) AS total_female_customers
FROM sales s
LEFT JOIN customer c ON s.customerkey = c.customerkey
LEFT JOIN store st ON s.storekey = st.storekey
WHERE s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY st.storecode
ORDER BY st.storecode;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

58 rows affected.

    storecode  total_male_customers  total_female_customers
0          -1                  4319                    4470
1           1                    28                      29
2           3                    46                      46
3           4                    40                      32
4           5                    65                      59
5           6                    38                      47
6           7                   102                      93
7           8                    93                      84
8           9                    66                      87
9          10                    75                      87
10         12                    15                      25
11         13                    12                      17
12         14                    24                      22
13         15                    13                      14
14         16                    17                      13
15         17                    19                       9
16         18                    19                      20
17         19                    45                      51
18         21                    47                      39
19         22                    48                      73
20         23                    46                      50
21         24                    44                      56
22         25                    41                      45
23         26                    45                      46
24         27                    40                      47
25         29                    37                      30
26         30                    41                      28
27         31                    51                      38
28         32                    49                      38
29         33                    46                      39
30         34                    49                      45
31         36                    34                      37
32         37                    46                      27
33         38                    40                      62
34         39                    47                      32
35         40                    61                      43
36         42                    37                      49
37         43                    60                      73
38         44                    75                      78
39         45                    73                      86
40         47                    47                      55
41         48                    75                      78
42         49                    71                      80
43         50                    83                      83
44         51                    74                      82
45         53                    64                      70
46         54                    86                      62
47         55                    82                      71
48         56                    75                      58
49         57                    66                      60
50         58                    73                      43
51         59                    84                      72
52         60                    71                      71
53         61                    74                      74
54         62                    74                      68
55         65                    90                      55
56         66                    67                      49
57         67                    71                      73

In [26]:
%%sql
/*
Calculate the total net revenue generated by each product color for different customer age groups in 2023.
This will help in understanding the revenue contribution of each product color across various age demographics.

Use SUM with CASE WHEN to calculate the revenue for each age group.
Define age groups as: 18 - 25, 26 - 35, 36-45, >45.
*/

SELECT
  p.color,
  SUM(CASE WHEN c.age BETWEEN 18 AND 25 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS revenue_18_25,
  SUM(CASE WHEN c.age BETWEEN 26 AND 35 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS revenue_26_35,
  SUM(CASE WHEN c.age BETWEEN 36 AND 45 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS revenue_36_45,
  SUM(CASE WHEN c.age > 45 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS revenue_above_45
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
LEFT JOIN customer c ON s.customerkey = c.customerkey
WHERE s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY p.color
ORDER BY p.color;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

17 rows affected.

          color  revenue_18_25  revenue_26_35  revenue_36_45  revenue_above_45
0         Azure        3090.69        1774.84        4038.86          18983.02
1         Black      943552.37     1238734.41     1341317.75        5358620.36
2          blue        1787.89         120.78         120.49           2332.40
3          Blue      106355.33      218804.28      288108.29        1052231.18
4         Brown      173724.20      328400.92      263582.64        1236801.78
5          Gold      103767.39      160052.97      208220.43         741488.38
6         Green       76812.16      210850.64       98165.38         464677.93
7          Grey      248999.05      340149.05      369611.65        1459721.76
8        Orange       26824.11       26681.98       22936.18         234684.26
9          Pink       59398.18      100738.15      114540.22         386449.24
10       Purple        1751.31        2199.15        3233.73           9360.40
11          Red      127271.43      160539.77      172419.66         668434.00
12       Silver      679973.36      948716.53      952253.88        3791172.41
13  Silver Grey       16531.91       17201.12       10310.53          89072.43
14  Transparent          83.02          59.49          52.96            215.82
15        White      793944.27     1044751.65     1117895.75        4320252.64
16       Yellow       14507.48       15160.79       16556.43          97391.98

In [35]:
%%sql
/*
Analyze the number of orders for products based on their price range and subcategoryname in 2023. This will help in understanding
the demand for products of different price ranges and sub-categories.

Use COUNT with CASE WHEN to count orders for different price ranges.
Define price ranges as: less than $1000, between $1000 and $2000, and greater than $2000.
Group by subcategoryname and order the results by subcategoryname from the product table.
*/

SELECT
  p.subcategoryname,
  COUNT(DISTINCT CASE WHEN p.price < 1000 THEN s.orderkey END) AS orders_price_less_than_1000,
  COUNT(DISTINCT CASE WHEN p.price BETWEEN 1000 AND 2000 THEN s.orderkey END) AS orders_price_between_1000_and_2000,
  COUNT(DISTINCT CASE WHEN p.price > 2000 THEN s.orderkey END) AS orders_price_greate_than_2000
FROM sales s
LEFT JOIN product p ON s.productkey = p.productkey
WHERE s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
GROUP BY p.subcategoryname
ORDER BY p.subcategoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

32 rows affected.

,subcategoryname,price_less_than_1000,price_between_1000_and_2000,price_greate_than_2000
0,Air Conditioners,352,0,0
1,Bluetooth Headphones,825,0,0
2,Boxed Games,1917,0,0
3,Camcorders,249,77,0
4,Cameras & Camcorders Accessories,358,0,0
5,Car Video,543,0,0
6,Cell phones Accessories,1518,0,0
7,Coffee Machines,280,41,0
8,Computers Accessories,1210,0,0
9,Desktops,2421,0,0
10,Digital Cameras,345,0,0
11,Digital SLR Cameras,591,0,0
12,Download Games,1251,0,0
13,Fans,228,0,0
14,Home & Office Phones,1376,0,0
15,Home Theater System,341,4,0
16,Lamps,229,0,0
17,Laptops,1027,199,0
18,Microwaves,567,0,0
19,Monitors,1243,0,0
20,Movie DVD,5359,0,0
21,MP4&MP3,342,0,0
22,"Printers, Scanners & Fax",1199,0,0
23,Projectors & Screens,1050,0,235
24,Recording Pen,429,0,0
25,Refrigerators,300,0,51
26,Smart phones & PDAs,3258,0,0
27,Televisions,778,315,105
28,Touch Screen Phones,2712,0,0
29,VCD & DVD,489,0,0
30,Washers & Dryers,50,136,58
31,Water Heaters,630,172,0

In [43]:
%%sql
/*
Calculate the total net revenue generated by stores of different sizes in each country in 2023.
This will help in understanding the revenue contribution from different store sizes across countries.

Use SUM with CASE WHEN to calculate revenue for different store sizes.
Define store sizes as: small (<1000 square meters), medium (1000-2000 square meters), and large (>2000 square meters).
Exclude "Online" stores under countryname.
Group the results by countryname and order them by countryname.
*/

SELECT
  st.countryname,
  SUM(CASE WHEN st.squaremeters < 1000 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS small_store_revenue,
  SUM(CASE WHEN st.squaremeters BETWEEN 1000 AND 2000 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS medium_store_revenue,
  SUM(CASE WHEN st.squaremeters > 2000 THEN s.quantity * s.netprice * s.exchangerate ELSE 0 END) AS large_store_revenue
FROM sales s
LEFT JOIN store st ON s.storekey = st.storekey
WHERE s.orderdate BETWEEN '2023-01-01' AND '2023-12-31'
AND st.countryname <> 'Online'
GROUP BY st.countryname
ORDER BY st.countryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,countryname,small_store_revenue,medium_store_revenue,large_store_revenue
0,Australia,152603.07,805753.93,332051.57
1,Canada,0.00,810136.00,1098302.94
2,France,387769.84,0.00,0.00
3,Germany,329324.58,1025798.82,192337.50
4,Italy,0.00,205734.46,142339.35
5,Netherlands,157601.88,448792.47,0.00
6,United Kingdom,0.00,642214.71,229729.64
7,United States,282562.90,5528952.03,246768.97