<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [9]:
%%sql

/*
Analyze the age of customers by calculating their age in months and days, and categorizing them into age groups. This final table will help in understanding the demographic distribution of the customer base.

Extract the year and month from the birthday to calculate the age in months.
Use the AGE function to calculate the age in days from CURRENT_DATE.
Categorize customers into age groups:
'Under 25'
'25-50'
'50+'.
*/

SELECT
  customerkey,
  EXTRACT(YEAR FROM AGE(CURRENT_DATE, birthday)) * 12 + EXTRACT(MONTH FROM AGE(CURRENT_DATE, birthday))
FROM customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

104990 rows affected.

        customerkey ?column?
0                15      735
1                23      434
2                36      743
3               120      955
4               180      854
...             ...      ...
104985      2099639      974
104986      2099656      970
104987      2099697      715
104988      2099711     1026
104989      2099743      316

[104990 rows x 2 columns]

In [2]:
%%sql

/*
Analyze the age of customers by calculating their age in months and days, and categorizing them into age groups.
This final table will help in understanding the demographic distribution of the customer base.

Extract the year and month from the birthday to calculate the age in months.
Use the AGE function to calculate the age in days from CURRENT_DATE.
Categorize customers into age groups:
'Under 25'
'25-50'
'50+'.
*/

SELECT
  customerkey,
  AGE(CURRENT_DATE, birthday) AS age_days,
  EXTRACT(YEAR FROM AGE(CURRENT_DATE, birthday)) * 12 + EXTRACT(MONTH FROM AGE(CURRENT_DATE, birthday)) AS age_months,
  CASE
    WHEN birthday >= CURRENT_DATE - INTERVAL '25 years' THEN 'Under 25'
    WHEN birthday >= CURRENT_DATE - INTERVAL '49 years' THEN '25 - 50'
    ELSE '50+'
  END AS age_group
FROM customer;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

104990 rows affected.

        customerkey   age_days age_months age_group
0                15 22375 days        735       50+
1                23 13203 days        434   25 - 50
2                36 22623 days        743       50+
3               120 29047 days        955       50+
4               180 25994 days        854       50+
...             ...        ...        ...       ...
104985      2099639 29638 days        974       50+
104986      2099656 29520 days        970       50+
104987      2099697 21750 days        715       50+
104988      2099711 31217 days       1026       50+
104989      2099743  9630 days        316   25 - 50

[104990 rows x 4 columns]

In [8]:
%%sql
/*
Classify stores with a 'Closed' status based on their operational lifespan in months.
This analysis helps in understanding how long stores were typically in operation before they were permanently closed. Your query should:
Calculate the lifespan_in_months for each store using its opendate and closedate.
Filter the data to include only stores with a status of 'Closed'.
Categorize each store's lifespan into one of the following, more granular ranges: 'Less than 5 years', '5-7 years', '7-9 years', or '9+ years'.
Order the final results by storekey.
*/
WITH store_lifespan AS (
  SELECT
    storekey,
    EXTRACT(YEAR FROM AGE(closedate, opendate)) * 12 + EXTRACT(MONTH FROM AGE(closedate, opendate)) as lifespan_months
  FROM store
  WHERE status = 'Closed'
)
SELECT
  storekey,
  lifespan_months,
  CASE
    WHEN lifespan_months / 12 < 5 THEN 'Less than 5 years'
    WHEN lifespan_months / 12 BETWEEN 5 AND 7 THEN '5-7 years'
    WHEN lifespan_months / 12 BETWEEN 7 AND 9 THEN '7-9 years'
    ELSE '9+ years'
  END AS lifespan_category
FROM store_lifespan
ORDER BY storekey

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

   storekey lifespan_months  lifespan_category
0        20             101          7-9 years
1       110              71          5-7 years
2       200              79          5-7 years
3       280              55  Less than 5 years
4       350              97          7-9 years
5       410              63          5-7 years
6       465              49  Less than 5 years
7       520              72          5-7 years

In [24]:
%%sql
/*
Analyze the historical lifetime of customers who churned at least 7 years ago.
This will help us understand past customer retention patterns.

For each customer:

Calculate their total lifetime (in months) from their start date (startdt) to their end date (enddt) from the customer table
Only include customers whose relationship ended at least 7 years ago
Categorize customers into lifetime ranges:
'1 - Less than 3 years'
'2 - 3-5 years'
'3 - 5-7 years'
'4 - 7+ years'
For each category, determine:
Number of customers
Percentage of total churned customers
Average customer lifetime in months
*/

WITH customers_lifespan AS (
  SELECT
    customerkey,
    EXTRACT(YEAR FROM AGE(enddt, startdt)) * 12 + EXTRACT(MONTH FROM AGE(enddt, startdt)) as lifespan_months
  FROM customer
  WHERE enddt IS NOT NULL
  AND enddt <= CURRENT_DATE - INTERVAL '7 years'
)
SELECT
  CASE
    WHEN lifespan_months / 12 < 3 THEN '1 - Less than 3 years'
    WHEN lifespan_months / 12 BETWEEN 3 AND 5 THEN '2 - 3-5 years'
    WHEN lifespan_months / 12 BETWEEN 5 AND 7 THEN '3 - 5-7 years'
    ELSE '4 - 7+ years'
  END AS lifetime_category,
  COUNT(*) AS customer_count,
  ROUND(COUNT(*) * 100 / (SELECT COUNT(*) FROM customers_lifespan), 2) AS churn_percentage,
  ROUND(AVG(lifespan_months), 1) AS avg_month_lifespan
FROM customers_lifespan
GROUP BY lifetime_category;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

       lifetime_category  customer_count churn_percentage avg_month_lifespan
0          3 - 5-7 years             568             3.00               72.8
1  1 - Less than 3 years             779             4.00               17.3
2           4 - 7+ years           15069            88.00              265.2
3          2 - 3-5 years             534             3.00               47.7

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

,active_range,customer_count,percentage_of_customers,avg_months_active
0,1 - Less than 3 years,779,4.60,17.3
1,2 - 3-5 years,534,3.15,47.7
2,3 - 5-7 years,568,3.35,72.8
3,4 - 7+ years,15069,88.90,265.2