<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [5]:
%%sql

WITH monthly_sales AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN CURRENT ROW AND CURRENT ROW
  ) AS net_revenue_current
FROM monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4465204.57
2   2023-03   2244316.52           2244316.52
3   2023-04   1162796.16           1162796.16
4   2023-05   2943005.99           2943005.99
5   2023-06   2864500.03           2864500.03
6   2023-07   2337639.34           2337639.34
7   2023-08   2623919.79           2623919.79
8   2023-09   2622774.85           2622774.85
9   2023-10   2551322.61           2551322.61
10  2023-11   2700103.38           2700103.38
11  2023-12   2928550.93           2928550.93

In [7]:
%%sql

WITH monthly_sales AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
  ) AS net_revenue_current
FROM monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4064817.96
2   2023-03   2244316.52           3354760.54
3   2023-04   1162796.16           1703556.34
4   2023-05   2943005.99           2052901.08
5   2023-06   2864500.03           2903753.01
6   2023-07   2337639.34           2601069.68
7   2023-08   2623919.79           2480779.57
8   2023-09   2622774.85           2623347.32
9   2023-10   2551322.61           2587048.73
10  2023-11   2700103.38           2625712.99
11  2023-12   2928550.93           2814327.15

In [8]:
%%sql

WITH monthly_sales AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING
  ) AS net_revenue_current
FROM monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           4064817.96
1   2023-02   4465204.57           3457984.14
2   2023-03   2244316.52           2624105.75
3   2023-04   1162796.16           2116706.22
4   2023-05   2943005.99           2323434.06
5   2023-06   2864500.03           2715048.45
6   2023-07   2337639.34           2608686.39
7   2023-08   2623919.79           2528111.33
8   2023-09   2622774.85           2599339.08
9   2023-10   2551322.61           2624733.61
10  2023-11   2700103.38           2726658.97
11  2023-12   2928550.93           2814327.15

In [10]:
%%sql

WITH monthly_sales AS (
  SELECT
    TO_CHAR(orderdate, 'YYYY-MM') AS month,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2023
  GROUP BY month
  ORDER BY month
)
SELECT
  month,
  net_revenue,
  AVG(net_revenue) OVER (
    ORDER BY month
    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
  ) AS net_revenue_current
FROM monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4064817.96
2   2023-03   2244316.52           3457984.14
3   2023-04   1162796.16           2884187.15
4   2023-05   2943005.99           2895950.92
5   2023-06   2864500.03           2890709.10
6   2023-07   2337639.34           2811699.14
7   2023-08   2623919.79           2788226.72
8   2023-09   2622774.85           2769843.18
9   2023-10   2551322.61           2747991.12
10  2023-11   2700103.38           2743637.69
11  2023-12   2928550.93           2759047.13

In [12]:
%%sql
/*
Calculate a 7-day rolling revenue window to analyze short-term trends in daily sales.
This helps smooth out daily fluctuations and highlight patterns in weekly performance.

Use a CTE to calculate the total net revenue per day by grouping sales by orderdate.
In the main query, use window functions with a 7-day frame to calculate:
The rolling sum of revenue (3 days before through 3 days after)
The rolling average of revenue over the same window
This rolling view helps detect local spikes, dips, and trends in daily revenue.
*/
WITH daily_sales AS (
  SELECT
    orderdate,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  GROUP BY orderdate
  ORDER BY orderdate
)
SELECT
  orderdate,
  net_revenue,
  SUM(net_revenue) OVER(ORDER BY orderdate ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING),
  AVG(net_revenue) OVER(ORDER BY orderdate ROWS BETWEEN 3 PRECEDING AND 3 FOLLOWING)
FROM daily_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  net_revenue       sum      avg
0     2015-01-01     11640.80  49734.14 12433.53
1     2015-01-02      5890.40  60084.01 12016.80
2     2015-01-03     19796.67  70613.06 11768.84
3     2015-01-05     12406.27  81917.34 11702.48
4     2015-01-06     10349.87  79523.44 11360.49
...          ...          ...       ...      ...
3289  2024-04-16     25098.99 192500.12 27500.02
3290  2024-04-17     32938.67 245226.68 35032.38
3291  2024-04-18     28408.76 243412.67 40568.78
3292  2024-04-19     48386.88 231712.73 46342.55
3293  2024-04-20     96879.43 206613.74 51653.44

[3294 rows x 4 columns]

In [13]:
%%sql
/*
Analyze short-term order revenue trends by calculating the total and average revenue of the next 10 orders following each order.
This helps identify periods of high or low revenue momentum based on future order values.

Use a CTE to calculate the net revenue per order by grouping on orderdate and orderkey.
In the main query, use window functions to calculate:
The rolling sum of revenue for the current and next 9 orders
The rolling average revenue over the same window
This gives a forward-looking view of how each order fits into the surrounding revenue stream.
*/

WITH daily_sales AS (
  SELECT
    orderdate,
    orderkey,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  GROUP BY orderdate, orderkey
  ORDER BY orderdate, orderkey
)
SELECT
  orderdate,
  orderkey,
  net_revenue,
  SUM(net_revenue) OVER(ORDER BY orderdate, orderkey ROWS BETWEEN CURRENT ROW AND 9 FOLLOWING),
  AVG(net_revenue) OVER(ORDER BY orderdate, orderkey ROWS BETWEEN CURRENT ROW AND 9 FOLLOWING
)
FROM daily_sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

83130 rows affected.

        orderdate  orderkey  net_revenue      sum     avg
0      2015-01-01      1000       486.77 11937.77 1193.78
1      2015-01-01      1001       108.75 13925.99 1392.60
2      2015-01-01      1002      3458.64 14611.85 1461.19
3      2015-01-01      1003       224.98 12452.78 1245.28
4      2015-01-01      1004      3246.38 12539.79 1253.98
...           ...       ...          ...      ...     ...
83125  2024-04-20   3398031      2624.34 10989.01 2197.80
83126  2024-04-20   3398032       275.67  8364.67 2091.17
83127  2024-04-20   3398033      4612.96  8089.00 2696.33
83128  2024-04-20   3398034      1251.81  3476.04 1738.02
83129  2024-04-20   3398035      2224.23  2224.23 2224.23

[83130 rows x 5 columns]

In [17]:
%%sql
/*
Analyze weekly revenue trends for the year 2022, and calculate cumulative, future, and specific week revenues to understand revenue performance across the entire year.

Use a CTE to compute total net revenue per week using TO_CHAR(orderdate, 'WW-YYYY').
In the main query, apply window functions to calculate:
The cumulative revenue up to the current week
The total future revenue from the current week forward
The revenue in the final week of the dataset
The revenue in the fifth week of the year
*/
WITH weekly_sales AS (
  SELECT
    TO_CHAR(orderdate, 'WW-YYYY') AS week,
    SUM(quantity * netprice * exchangerate) AS net_revenue
  FROM sales
  WHERE EXTRACT(YEAR FROM orderdate) = 2022
  GROUP BY week
  ORDER BY week
)
SELECT
  week,
  net_revenue,
  SUM(net_revenue) OVER(ORDER BY week ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS cumulative_revenue,
  SUM(net_revenue) OVER(ORDER BY week ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) AS future_revenue,
  LAST_VALUE(net_revenue) OVER(ORDER BY week ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_value,
  NTH_VALUE(net_revenue, 5) OVER(ORDER BY week ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS fifth_week_revenue
FROM weekly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

53 rows affected.

,week,net_revenue,cumulative_revenue,future_revenue,last_value,fifth_week_revenue
0,01-2022,1025757.01,1025757.01,44864557.21,231514.53,891005.79
1,02-2022,757259.07,1783016.08,43838800.20,231514.53,891005.79
2,03-2022,757529.40,2540545.48,43081541.13,231514.53,891005.79
3,04-2022,774653.48,3315198.96,42324011.73,231514.53,891005.79
4,05-2022,891005.79,4206204.74,41549358.25,231514.53,891005.79
5,06-2022,858310.66,5064515.40,40658352.46,231514.53,891005.79
6,07-2022,1401973.86,6466489.26,39800041.81,231514.53,891005.79
7,08-2022,1504683.91,7971173.17,38398067.95,231514.53,891005.79
8,09-2022,1041194.44,9012367.61,36893384.04,231514.53,891005.79
9,10-2022,831557.40,9843925.01,35852189.59,231514.53,891005.79
10,11-2022,809165.74,10653090.75,35020632.20,231514.53,891005.79
11,12-2022,420062.06,11073152.81,34211466.45,231514.53,891005.79
12,13-2022,258390.96,11331543.77,33791404.39,231514.53,891005.79
13,14-2022,170302.09,11501845.86,33533013.44,231514.53,891005.79
14,15-2022,229969.87,11731815.74,33362711.34,231514.53,891005.79
15,16-2022,398595.67,12130411.41,33132741.47,231514.53,891005.79
16,17-2022,715844.32,12846255.73,32734145.80,231514.53,891005.79
17,18-2022,994282.69,13840538.42,32018301.48,231514.53,891005.79
18,19-2022,1046455.60,14886994.02,31024018.79,231514.53,891005.79
19,20-2022,1062039.60,15949033.62,29977563.19,231514.53,891005.79
20,21-2022,982864.32,16931897.94,28915523.59,231514.53,891005.79
21,22-2022,1054127.57,17986025.51,27932659.27,231514.53,891005.79
22,23-2022,1096161.11,19082186.61,26878531.70,231514.53,891005.79
23,24-2022,1096215.46,20178402.07,25782370.59,231514.53,891005.79
24,25-2022,1073975.83,21252377.90,24686155.13,231514.53,891005.79
25,26-2022,1152650.88,22405028.78,23612179.30,231514.53,891005.79
26,27-2022,953687.72,23358716.50,22459528.42,231514.53,891005.79
27,28-2022,990275.77,24348992.27,21505840.71,231514.53,891005.79
28,29-2022,741382.36,25090374.63,20515564.94,231514.53,891005.79
29,30-2022,435361.52,25525736.15,19774182.58,231514.53,891005.79
30,31-2022,501116.87,26026853.01,19338821.06,231514.53,891005.79
31,32-2022,894399.79,26921252.81,18837704.19,231514.53,891005.79
32,33-2022,943243.07,27864495.88,17943304.40,231514.53,891005.79
33,34-2022,912871.48,28777367.36,17000061.33,231514.53,891005.79
34,35-2022,835043.11,29612410.47,16087189.85,231514.53,891005.79
35,36-2022,777100.54,30389511.01,15252146.74,231514.53,891005.79
36,37-2022,997322.70,31386833.71,14475046.20,231514.53,891005.79
37,38-2022,921002.75,32307836.45,13477723.50,231514.53,891005.79
38,39-2022,884674.14,33192510.59,12556720.75,231514.53,891005.79
39,40-2022,915296.71,34107807.30,11672046.62,231514.53,891005.79
40,41-2022,927494.60,35035301.90,10756749.91,231514.53,891005.79
41,42-2022,859845.77,35895147.67,9829255.31,231514.53,891005.79
42,43-2022,873112.26,36768259.93,8969409.54,231514.53,891005.79
43,44-2022,854464.98,37622724.91,8096297.27,231514.53,891005.79
44,45-2022,902704.88,38525429.79,7241832.30,231514.53,891005.79
45,46-2022,772228.63,39297658.43,6339127.41,231514.53,891005.79
46,47-2022,836526.26,40134184.69,5566898.78,231514.53,891005.79
47,48-2022,710474.60,40844659.28,4730372.52,231514.53,891005.79
48,49-2022,792454.24,41637113.52,4019897.93,231514.53,891005.79
49,50-2022,905534.84,42542648.36,3227443.69,231514.53,891005.79
50,51-2022,927345.40,43469993.76,2321908.85,231514.53,891005.79
51,52-2022,1163048.92,44633042.68,1394563.45,231514.53,891005.79
52,53-2022,231514.53,44864557.21,231514.53,231514.53,891005.79

In [ ]:
%%sql

In [ ]:
%%sql